#106: Use VSCL
exasol/row-level-security-lua pull request #108
Opened 2022-03-23 08:00 UTC by redcatbear

Closes #106.

2022-03-25 06:17 UTC, kaklakariada requested changes

2022-03-25 06:17 UTC, kaklakariada commented on src/main/lua/exasolrls/MetadataReader.lua
> +            log.debug('Found table "' .. table_id .. '" (' .. #columns .. ' columns). Protection: ' .. protection)
Use placeholders instead of string concatenation

2022-04-11 10:31 UTC, redcatbear commented on tools/runtests.sh
> +    busted -c
Done.

2022-04-11 10:31 UTC, redcatbear commented on src/main/lua/exasolrls/RlsAdapter.lua
> +    return "Row-level Security adapter (LUA)"
Done.

2022-04-11 14:56 UTC, kaklakariada submitted a review, later dismissed

2022-04-12 13:29 UTC, kaklakariada approved these changes

2022-04-12 13:29 UTC, kaklakariada commented on pom.xml
> +                            <executable>amalg.lua</executable>
👍

2022-04-13 06:29 UTC, kaklakariada approved these changes

2022-04-13 08:39 UTC, kaklakariada approved these changes

2022-04-13 08:42 UTC, merged